Adding in schema definition folder and schema definition template
CuBoulder/ucb2021_base pull request #18
Opened 2021-06-17 19:58 UTC by jcsparks

Adding in schema definition folder and schema definition template.

2021-06-22 15:57 UTC, cathysnider requested changes
Suggested Change: add 'example' and parens to the schema.org definition link. 

## Schema.org definition link : (example: https://schema.org/Person)

2021-06-23 02:09 UTC, AlanBCole requested changes

2021-06-23 02:09 UTC, AlanBCole commented on schema_definitions/schema_defintion_template.md
> +## Schema.org definition link : https://schema.org/Person
Remove link to Person

2021-06-23 14:24 UTC, jcsparks commented on schema_definitions/schema_defintion_template.md
> +## Schema.org definition link : https://schema.org/Person
I didn't think it was that confusing... but okay.

2021-06-23 15:03 UTC, cathysnider approved these changes

2021-06-23 15:52 UTC, AlanBCole approved these changes

2021-06-23 16:30 UTC, merged