Form page created
CuBoulder/ucb2021_base pull request #190
Opened 2022-05-02 14:33 UTC by jacob-korf

2022-05-02 17:10 UTC, jacob-korf commented
Closes #177 
Closes #174 
Closes #144

2022-05-02 18:47 UTC, jnicholCU commented
All working from my tests.

2022-05-03 23:03 UTC, jcsparks requested changes
This all looks and works well.  We should have Kevin review from a UI/UX perspective.  

We need to add a pathauto patter for generating form node aliases automatically.

2022-05-12 19:41 UTC, jcsparks approved these changes

2022-05-12 19:42 UTC, merged