Create Article Schema
CuBoulder/ucb2021_base pull request #27
Opened 2021-06-29 18:22 UTC by cathysnider

2021-06-30 16:12 UTC, jcsparks commented on schema_definitions/article.md
> + |Image: Photo | Y | N | Image | image |  |  |  |
We won't be using the Image type in D9, the Media module is in core now and fully matured to the point where there's no reason not to use Media for digital files wherever possible.

2021-06-30 16:13 UTC, jcsparks commented on schema_definitions/article.md
> + |Image: Thumbnail | N | N | image | image |  |  |  |
We may not need a separate image for thumbnail either... it's possible that Media has this included for image file types.

2021-06-30 16:17 UTC, jcsparks commented on schema_definitions/article.md
> + |Date Display | N | Y | list (text) |  -  |  |  | A dropdown to show or hide date. |
Does this just default to the content publish date?  Wouldn't it be more flexible to he an actual datetime field here... we wouldn't need a display flag then, if it's filled out we show it, if it's not then we don't.

2021-06-30 16:17 UTC, jcsparks requested changes
Images should be moved to Media for sure... need to look at datetime field as well.

2021-06-30 20:10 UTC, cathysnider commented on schema_definitions/article.md
> + |Date Display | N | Y | list (text) |  -  |  |  | A dropdown to show or hide date. |
That would be one way of solving the problem. We also offer the option to schedule publication; perhaps we'd want to tie these two functionalities together in some way.

2021-06-30 20:18 UTC, cathysnider commented on schema_definitions/article.md
> + |Image: Thumbnail | N | N | image | image |  |  |  |
People do upload several images to their articles sometimes. We'll need a way for them to mark which image is to be used as the thumbnail.

2021-08-10 20:39 UTC, jcsparks approved these changes
Looks like a good start.  Might want to make a more advanced new story content type later on.

2021-08-10 20:39 UTC, merged